services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: spotify-encora-frontend
    ports:
      - "8080:3000"
    networks:
      - app-network
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: spotify-encora-api
    ports:
      - "3000:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
